markdown: kramdown

remote_theme: pages-themes/midnight@v0.2.0
title: Zeger Hendrikse
description: TDD, physics, and mathematics
show_downloads: false

url: "https://www.hendrikse.name/" # the base hostname & protocol for your site
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-sitemap 
